[Paths]
GPU001=
GPU014=
GPU018=
OutputPath=

[Runtime]
;check interval in seconds
CheckInterval=30

[Data]
ApplicationName=Daltonmonitor
DaltonIdentifiers=DAL
WorkshopIdentifiers=DAL+
MentorIdentifiers=M5A,M5B,M5C,M5D,M6A,M6B,M6C,M6D,M7A,M7B,M7C,M7D,M8A,M8B,M8C,M8D,M9A,M9B,M9C,M9D,M10A,M10B,M10C,M10D,MEF,MQ1,MQ2

[Html]
ShowWorkshops=true
ShowVacationDays=true
;the amount of future days that should be baked into the html
PreviewingDays=3
;whether labels should be used or not
ShowLabels=true

[Style]
;application background color
BackgroundColor=00bbff

;background color of the different elements
ElementColor=90caf9

;color used for the normal texts in the frontend
TextColor=000000
;color used for the texts when room or teacher is changed
TextColorDataChange=c1121f

;background color used for the tags
TagColor=bbdefb

;border information (color,padding)
Border=bbdefb,0.1

;if element shadow should be enabled or not
EnableShadow=true